# Generated by Django 4.0.2 on 2022-03-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
