# Generated by Django 4.0.2 on 2022-03-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
