# Generated by Django 4.0.2 on 2022-04-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='modiefied_at',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='pledge',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
