# Generated by Django 4.0.2 on 2022-04-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_rename_modiefied_at_comment_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
